### ISSUE TITLE
Errors after upgrade to 2026.2.2

### ISSUE THREAD

**Issue by diegofrances** [AlexxIT/VacuumZones#25]
Hi, I am getting the below errors after upgrading to 2026.2.2
```
Registrador: homeassistant.setup
Fuente: setup.py:506
Ocurrió por primera vez: 02:21:11 (1 ocurrencia)
Última vez registrado: 02:21:11

Unable to prepare setup for platform 'vacuum_zones.vacuum': Platform not found (cannot import name 'STATE_CLEANING' from 'homeassistant.components.vacuum' (/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py)).

Registrador: homeassistant.util.loop
Fuente: util/loop.py:77
Ocurrió por primera vez: 02:21:11 (1 ocurrencia)
Última vez registrado: 02:21:11

Detected blocking call to import_module with args ('custom_components.vacuum_zones.vacuum',) in /usr/src/homeassistant/homeassistant/loader.py, line 1307: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 160, in _async_component_platform_discovered await self.async_setup_platform(platform, {}, info) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 251, in async_setup_platform platform = await async_prepare_setup_platform( File "/usr/src/homeassistant/homeassistant/setup.py", line 547, in async_prepare_setup_platform platform = await integration.async_get_platform(domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 1111, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1176, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1101, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1275, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1307, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")
```

**Comment by AlexxIT** [comment]
You using outdated integration version.

**Comment by diegofrances** [comment]
Hi Alexx,

You are 100% right, no idea why the upgrade notification did not show up until today but after the upgrade to v1.1.1 the error is gone.

**Comment by AlexxIT** [comment]
This is a HACS bug after one of the updates. I have such complaints in every project.
